In [ ]:
#task 1
class Student:
  ID = 0
  def __init__(self, name, dept, age, cgpa):
    self.name = name
    self.dept = dept
    self.age = age
    self.cgpa = cgpa
    Student.ID += 1
  def showDetails(self):
    print("ID:", Student.ID)
    print("Name:", self.name)
    print("Department:", self.dept)
    print("Age:", self.age)
    print("CGPA:", self.cgpa)

  @classmethod
  def from_String(cls, info):
    name, dept, age, cgpa = info.split("-")
    obj = cls(name, dept, age, cgpa)
    return obj

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
#task 2
class Passenger:
  count = 0
  def __init__(self, name):
    self.name = name
    self.fare = 450
    self.weight = 0
    Passenger.count += 1
  def set_bag_weight(self, weight):
    self.weight = weight
    if 20<self.weight<=50:
      self.fare += 50
    elif self.weight>50:
      self.fare += 100
  def printDetail(self):
    print("Name:", self.name)
    print("Bus fare:", self.fare, "Taka")


print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus fare: 550 Taka
=========================
Name: Carol
Bus fare: 450 Taka
=========================
Name: Mike
Bus fare: 500 Taka
=========================
Total Passenger: 3

In [ ]:
#task 3
class Travel:
  count = 0
  def __init__(self, source, destination):
    self.source = source
    self.destination = destination
    self.flight_time = 1
    Travel.count += 1
  def set_time(self, time):
    self.flight_time = time
  def display_travel_info(self):
    return f"Source: {self.source} \nDestination: {self.destination} \nFlight time: {self.flight_time}:00"
  def set_destination(self, destination):
    self.destination = destination
  def set_source(self, source):
    self.source = source


print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight time: 1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight time: 23:00
=======================
Source: Dhaka
Destination: Germany
Flight time: 15:00
=======================
Source: Malaysia
Destination: Canada
Flight time: 9:00
=======================
No. of Traveller = 4

In [ ]:
#task 4
class Student:
  total_student = 0
  bracu_student = 0
  other_student = 0
  def __init__(self, name, dept, uni="BRAC University"):
    self.name = name
    self.dept = dept
    self.uni = uni
    Student.total_student += 1
    if self.uni == "BRAC University":
      Student.bracu_student += 1
    else:
      Student.other_student += 1
  def individualDetail(self):
    print("Name:", self.name)
    print("Department:", self.dept)
    print("Institution", self.uni)
  @classmethod
  def printDetails(cls):
    print("Total Student(s):",  cls.total_student)
    print("BRAC University Student(s):", cls.bracu_student)
    print("Other Institution Student(s):", cls.other_student)
  @classmethod
  def createStudent(cls, name, dept, uni="BRAC University"):
    obj = cls(name, dept, uni)
    return obj

Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1