In [ ]:
#homework - task 1
class Shape:
  def __init__(self, name='Default', height=0, base=0):
    self.area = 0
    self.name = name
    self.height = height
    self.base = base
  def get_height_base(self):
    return "Height: "+str(self.height)+", Base: "+str(self.base)

class triangle(Shape):
  def __init__(self, name = "Default", height = 0, base = 0):
    super().__init__(name, height, base)
  def calcArea(self):
    self.area = 0.5*self.height*self.base
  def printDetail(self):
    return f"Shape name: {self.name} \nHeight: {self.height}, Base: {self.base} \nArea: {self.area}"

class trapezoid(Shape):
  def __init__(self, name, height, base, side_A):
    super().__init__(name, height, base)
    self.side_A = side_A
  def calcArea(self):
    self.area = ((self.base + self.side_A)/2) * self.height
  def printDetail(self):
    return f"Shape name: {self.name} \nHeight: {self.height}, Base: {self.base}, Side_A: {self.side_A} \nArea: {self.area}"



tri_default = triangle()
tri_default.calcArea()
print(tri_default.printDetail())
print('--------------------------')
tri = triangle('Triangle', 10, 5)
tri.calcArea()
print(tri.printDetail())
print('---------------------------')
trap = trapezoid('Trapezoid', 10, 6, 4)
trap.calcArea()
print(trap.printDetail())

Shape name: Default
Height: 0, Base: 0
Area: 0.0
--------------------------
Shape name: Triangle
Height: 10, Base: 5
Area: 25.0
---------------------------
Shape name: Trapezoid
Height: 10, Base: 6, Side_A: 4
Area: 50.0

In [ ]:
#taks 2
class SportsPerson:
  def __init__(self, team_name, name, role):
    self.__team = team_name
    self.__name = name
    self.role = role
    self.earning_per_match = 0
  def get_name_team(self):
    return 'Name: '+self.__name+', Team Name: ' + self.__team

class Player(SportsPerson):
  def __init__(self, team_name, name, role, goal, matches):
    super().__init__(team_name, name, role)
    self.goal = goal
    self.matches = matches
    self.earning_per_match = (self.goal * 1000) + (self.matches * 10)
    self.ratio = 0
  def calculate_ratio(self):
    self.ratio = self.goal / self.matches
  def print_details(self):
    print(super().get_name_team())
    print(f"Team Role: {self.role}")
    print(f"Total Goal: {self.goal}, Total Played: {self.matches}")
    print(f"Goal Ratio: {self.ratio}")
    print(f"Match Earning: {self.earning_per_match}K")

class Manager(SportsPerson):
  def __init__(self, team_name, name, role, wins):
    super().__init__(team_name, name, role)
    self.wins = wins
    self.earning_per_match = self.wins * 1000
  def print_details(self):
    print(super().get_name_team())
    print("Team Role: ", self.role)
    print("Total Win: ", self.wins)
    print(f"Match Earning: {self.earning_per_match}K")


player_one = Player('Al-Nassr', 'Ronaldo', 'Striker', 25, 32)
player_one.calculate_ratio()
player_one.print_details()
print('------------------------------------------')
manager_one = Manager('Real Madrid', 'Zidane', 'Manager', 25)
manager_one.print_details()

Name: Ronaldo, Team Name: Al-Nassr
Team Role: Striker
Total Goal: 25, Total Played: 32
Goal Ratio: 0.78125
Match Earning: 25320K
------------------------------------------
Name: Zidane, Team Name: Real Madrid
Team Role:  Manager
Total Win:  25
Match Earning: 25000K

In [ ]:
#task 3
class KK_tea:
  total_sale = {"KK Regular Tea": 0}
  def __init__(self, price, tea_bags = 50):
    self.name = "KK Regular Tea"
    self.tea_bags = tea_bags
    self.price = price
    self.weight = self.tea_bags * 2
    self.status = False
  def product_detail(self):
    print(f"Name: {self.name}, Weight: {self.weight}")
    print(f"Tea Bags: {self.tea_bags}, Price: {self.price}")
    print(f"Status: {self.status}")
  @classmethod
  def update_sold_status_regular(cls, *others):
    for i in others:
      i.status = True
      KK_tea.total_sale[i.name] += 1
  @classmethod
  def total_sales(cls):
    print(f"Total sales: {cls.total_sale}")


class KK_flavoured_tea(KK_tea):
  def __init__(self, name, price, tea_bags):
    super().__init__(price, tea_bags)
    self.name = "KK "+name+" Tea"
    KK_tea.total_sale.update({self.name: 0})
  @classmethod
  def update_sold_status_flavoured(cls, *others):
    super().update_sold_status_regular(*others)



t1 = KK_tea(250)
print("-----------------1-----------------")
t1.product_detail()
print("-----------------2-----------------")
KK_tea.total_sales()
print("-----------------3-----------------")
t2 = KK_tea(470, 100)
t3 = KK_tea(360, 75)
KK_tea.update_sold_status_regular(t1, t2, t3)
print("-----------------4-----------------")
t3.product_detail()
print("-----------------5-----------------")
KK_tea.total_sales()
print("-----------------6-----------------")
t4 = KK_flavoured_tea("Jasmine", 260, 50)
t5 = KK_flavoured_tea("Honey Lemon", 270, 45)
t6 = KK_flavoured_tea("Honey Lemon", 270, 45)
print("-----------------7-----------------")
t4.product_detail()
print("-----------------8-----------------")
t6.product_detail()
print("-----------------9-----------------")
KK_flavoured_tea.update_sold_status_flavoured(t4, t5, t6)
print("-----------------10-----------------")
KK_tea.total_sales()

-----------------1-----------------
Name: KK Regular Tea, Weight: 100
Tea Bags: 50, Price: 250
Status: False
-----------------2-----------------
Total sales: {'KK Regular Tea': 0}
-----------------3-----------------
-----------------4-----------------
Name: KK Regular Tea, Weight: 150
Tea Bags: 75, Price: 360
Status: True
-----------------5-----------------
Total sales: {'KK Regular Tea': 3}
-----------------6-----------------
-----------------7-----------------
Name: KK Jasmine Tea, Weight: 100
Tea Bags: 50, Price: 260
Status: False
-----------------8-----------------
Name: KK Honey Lemon Tea, Weight: 90
Tea Bags: 45, Price: 270
Status: False
-----------------9-----------------
-----------------10-----------------
Total sales: {'KK Regular Tea': 3, 'KK Jasmine Tea': 1, 'KK Honey Lemon Tea': 2}

In [ ]:
#task 4
import math
class TwoDVector:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def add2DVectors(self, *vectors):
    for i in vectors:
      self.x += i.x
      self.y += i.y
  def print2DVector(self):
    if self.y >= 0:
        y = "+ "+str(self.y)
    else:
        y = str(self.y)
    print(f"{self.x}i {y}j")


class ThreeDVector(TwoDVector):
  def __init__(self, x, y, z):
    super().__init__(x, y)
    self.z = z
  def add3DVectors(self, *vectors):
    super().add2DVectors(*vectors)
    for i in vectors:
      self.z += i.z
  def multiplyScalar(self, num):
    self.x *= num
    self.y *= num
    self.z *= num
  def calculateLength(self):
    length = math.sqrt((self.x**2) + (self.y**2) + (self.z ** 2))
    return length
  def print3DVector(self):
    if self.z >= 0:
      z = f"+ {self.z}"
    else:
      z = str(self.z)
    if self.y >= 0:
      y = f"+ {self.y}"
    else:
      y = str(self.y)
    print(f"{self.x}i {y}j {z}k")


TwoDV1 = TwoDVector(5, 6)
TwoDV2 = TwoDVector(3, 7)
TwoDV3 = TwoDVector(1, 8)
print("===============")
TwoDV1.add2DVectors(TwoDV2, TwoDV3)
TwoDV1.print2DVector()
print("===============")
ThreeDV1 = ThreeDVector(5, 6, 1)
ThreeDV2 = ThreeDVector(1, 9,-7)
ThreeDV3 = ThreeDVector(8, 2, 4)
print("===============")
ThreeDV1.add3DVectors(ThreeDV2,ThreeDV3)
ThreeDV1.print3DVector()
print("===============")
ThreeDV1.multiplyScalar(3)
ThreeDV1.print3DVector()
print("===============")
print(ThreeDV1.calculateLength())

===============
9i + 21j
===============
===============
14i + 17j -2k
===============
42i + 51j -6k
===============
66.34003316248794